#!/bin/bash

#
# Private Functions
#

function _parseGitBranch {
	git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

function _set_exports {
	# export QT_SELECT=4

	export PATH=${HOME}/bin:${HOME}/go/bin:${HOME}/.local/bin:${PATH}

	export EDITOR=nvim

	#export ANDROID_SDK_ROOT=${HOME}/Android/Sdk
	#export ANDROID_NDK_HOME=${HOME}/Android/Sdk/ndk/25.2.9519653
	export ANDROID_NDK_HOME=${HOME}/Downloads/android-ndk-r25c/
	#export ANDROID_HOME=${HOME}/Android/Sdk

	export CAPACITOR_ANDROID_STUDIO_PATH=$(which android-studio)

	export HISTSIZE=1000
	export HISTFILESIZE=
}


function _set_aliases {
	alias ls='ls --color=auto'
	alias grep='grep --colour=auto'
	alias egrep='egrep --colour=auto'
	alias fgrep='fgrep --colour=auto'
	alias yay="yay --color=auto"
	alias pacman="pacman --color=auto"

	alias john="${HOME}/src/john/run/john"
	alias ip="ip -c"
	alias tree="tree -C"
	alias bat="bat --theme gruvbox-dark"
	alias tt="tt -theme gruvbox-dark"
	alias less="less -R"
	alias markdown-preview="grip"

	# git
	alias gst="git status"
	alias gc="git commit"
	alias gl="git pull"
	alias glo="git log --oneline"
	alias gp="git push"
	alias ga="git add"
	alias gaa="git add --all"
	alias gb="git branch"
	alias gba="git branch --all"
	alias gr="git remote"
	alias grv="git remote --verbose"
	alias gd="git diff"
	alias gdc="git diff --cached"

	# cd
	alias ..="cd .."
	alias ...="cd ../../"
	alias ....="cd ../../../"
	alias .....="cd ../../../../"
	alias ......="cd ../../../../../"
	alias .......="cd ../../../../../../"
	alias ........="cd ../../../../../../../"

	#alias cp="cp -i"                          # confirm before overwriting something
	alias df='df -h'                          # human-readable sizes
	alias free='free -m'                      # show sizes in MB
	alias more=less

	# ls
	alias la="ls -a"
	alias ll="ls -l"
	alias lla="ls -la"
}

#
# Functions
#

# ex - archive extractor
# usage: ex <file>
function ex {
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

#
# Main
#

[ -r /usr/share/bash-completion/bash_completion ] && . /usr/share/bash-completion/bash_completion
[ ! -e ~/.inputrc ] && echo '$include /etc/inputrc' > ${HOME}/.inputrc

# Change the window title of X terminals
case ${TERM} in
	xterm*|rxvt*|Eterm*|aterm|kterm|gnome*|interix|konsole*)
		PROMPT_COMMAND='echo -ne "\033]0;${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\007"'
		;;
	screen*)
		PROMPT_COMMAND='echo -ne "\033_${USER}@${HOSTNAME%%.*}:${PWD/#$HOME/\~}\033\\"'
		;;
esac

use_color=true

# Set colorful PS1 only on colorful terminals.
# dircolors --print-database uses its own built-in database
# instead of using /etc/DIR_COLORS.  Try to use the external file
# first to take advantage of user additions.  Use internal bash
# globbing instead of external grep binary.
safe_term=${TERM//[^[:alnum:]]/?}   # sanitize TERM
match_lhs=""
[[ -f ~/.dir_colors   ]] && match_lhs="${match_lhs}$(<~/.dir_colors)"
[[ -f /etc/DIR_COLORS ]] && match_lhs="${match_lhs}$(</etc/DIR_COLORS)"
[[ -z ${match_lhs}    ]] \
	&& type -P dircolors >/dev/null \
	&& match_lhs=$(dircolors --print-database)
[[ $'\n'${match_lhs} == *$'\n'"TERM "${safe_term}* ]] && use_color=true

if ${use_color} ; then
	# Enable colors for ls, etc.  Prefer ~/.dir_colors #64489
	if type -P dircolors >/dev/null ; then
		if [[ -f ~/.dir_colors ]] ; then
			eval $(dircolors -b ~/.dir_colors)
		elif [[ -f /etc/DIR_COLORS ]] ; then
			eval $(dircolors -b /etc/DIR_COLORS)
		fi
	fi

	if [[ ${EUID} == 0 ]] ; then
		PS1='\[\033[01;31m\][\h\[\033[01;36m\] \W\[\033[01;31m\]]\[\033[01;34m\]$(_parseGitBranch)\[\033[01;32m\] \$\[\033[00m\] '
	else
		PS1='\[\033[01;32m\][\u@\h\[\033[01;37m\] \W\[\033[01;32m\]]\[\033[01;34m\]$(_parseGitBranch)\[\033[01;32m\] \$\[\033[00m\] '
	fi


else
	if [[ ${EUID} == 0 ]] ; then
		# Show root@ when we don't have colors
		PS1='\u@\h \W \$ '
	else
		PS1='\u@\h \w \$ '
	fi
fi

unset use_color safe_term match_lhs sh

xhost +local:root > /dev/null 2>&1

# Enable checkwinsize so that bash will check the terminal size when
# it regains control.  #65623
shopt -s checkwinsize

shopt -s expand_aliases

# Enable history appending instead of overwriting.  #139609
shopt -s histappend

# Enable vi mode
set -o vi

# Ignore case sensitive on tab completion
bind 'set completion-ignore-case on'

bind ^l:clear

# Enable z
[[ -r "/usr/share/z/z.sh" ]] && source /usr/share/z/z.sh
[[ -r "/usr/libexec/z.sh" ]] && source /usr/libexec/z.sh

# Do exports and set aliases
_set_exports
_set_aliases
