#! /bin/bash

primary_monitor=eDP-1

#
# monitor(s) 
#
xrandr \
  --output ${primary_monitor} \
  --scale 0.6x0.6 \
  --primary \
  --auto

bspc monitor $primary_monitor -d 1 2 3 4 5 6 7 8 9


#
# autostart
#
wmname LG3D
pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom &
pgrep -x nm-applet > /dev/null || nm-applet &
#pgrep -x volumeicon > /dev/null || volumeicon &
pgrep -x unclutter > /dev/null || unclutter -idle 0.5 -root &
pgrep -x lxqt-policykit-agent > /dev/null || lxqt-policykit-agent &

# (re)start polybar
killall --quiet polybar

# wait until process have been shut down
while pgrep -u $UID -x polybar > /dev/null; do : ; done

MONITOR=${primary_monitor} polybar --reload primary &

feh --bg-scale \
  "$HOME/Pictures/Wallpaper/16_10/gruvbox.webp"

#
# bspwm
#

bspc config border_radius              4
bspc config border_width               2
bspc config window_gap                 15
bspc config top_padding                25
bspc config bottom_padding             10
bspc config left_padding               0
bspc config right_padding              0
bspc config single_monocle             true 
bspc config click_to_focus             true
bspc config split_ratio                0.50
bspc config borderless_monocle         true
bspc config gapless_monocle            true
bspc config focus_by_distance          true
bspc config focus_follows_pointer      true
bspc config history_aware_focus        true
bspc config remove_disabled_monitors   true
bspc config merge_overlapping_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#5e81ac"
bspc config presel_feedback_color "#5e81ac"
bspc config urgent_border_color   "#dd2727"

bspc rule -a Gimp state=floating follow=on
